/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type ModuleDataStruct = { modules: BigNumberish[]; args: BytesLike[] };

export type ModuleDataStructOutput = [number[], string[]] & {
  modules: number[];
  args: string[];
};

export type TimeStruct = { nextExec: BigNumberish; interval: BigNumberish };

export type TimeStructOutput = [BigNumber, BigNumber] & {
  nextExec: BigNumber;
  interval: BigNumber;
};

export interface IOpsInterface extends utils.Interface {
  functions: {
    "cancelTask(bytes32)": FunctionFragment;
    "createTask(address,bytes,(uint8[],bytes[]),address)": FunctionFragment;
    "createTaskNoPrepayment(address,bytes4,address,bytes,address)": FunctionFragment;
    "exec(address,address,bytes,(uint8[],bytes[]),uint256,address,bool,bool)": FunctionFragment;
    "gelato()": FunctionFragment;
    "getFeeDetails()": FunctionFragment;
    "getTaskIdsByUser(address)": FunctionFragment;
    "setModule(uint8[],address[])": FunctionFragment;
    "taskTreasury()": FunctionFragment;
    "timedTask(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [string, BytesLike, ModuleDataStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTaskNoPrepayment",
    values: [string, BytesLike, string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "exec",
    values: [
      string,
      string,
      BytesLike,
      ModuleDataStruct,
      BigNumberish,
      string,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "gelato", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFeeDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskIdsByUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setModule",
    values: [BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "taskTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timedTask",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTaskNoPrepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gelato", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeeDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaskIdsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setModule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "taskTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timedTask", data: BytesLike): Result;

  events: {};
}

export interface IOps extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IOpsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancelTask(
      taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createTask(
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      feeToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createTaskNoPrepayment(
      _execAddress: string,
      _execSelector: BytesLike,
      _resolverAddress: string,
      _resolverData: BytesLike,
      _feeToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exec(
      taskCreator: string,
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      txFee: BigNumberish,
      feeToken: string,
      useTaskTreasuryFunds: boolean,
      revertOnFailure: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    gelato(overrides?: CallOverrides): Promise<[string]>;

    getFeeDetails(overrides?: CallOverrides): Promise<[BigNumber, string]>;

    getTaskIdsByUser(
      taskCreator: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    setModule(
      modules: BigNumberish[],
      moduleAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    taskTreasury(overrides?: CallOverrides): Promise<[string]>;

    timedTask(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[TimeStructOutput]>;
  };

  cancelTask(
    taskId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createTask(
    execAddress: string,
    execData: BytesLike,
    moduleData: ModuleDataStruct,
    feeToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createTaskNoPrepayment(
    _execAddress: string,
    _execSelector: BytesLike,
    _resolverAddress: string,
    _resolverData: BytesLike,
    _feeToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exec(
    taskCreator: string,
    execAddress: string,
    execData: BytesLike,
    moduleData: ModuleDataStruct,
    txFee: BigNumberish,
    feeToken: string,
    useTaskTreasuryFunds: boolean,
    revertOnFailure: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  gelato(overrides?: CallOverrides): Promise<string>;

  getFeeDetails(overrides?: CallOverrides): Promise<[BigNumber, string]>;

  getTaskIdsByUser(
    taskCreator: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  setModule(
    modules: BigNumberish[],
    moduleAddresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  taskTreasury(overrides?: CallOverrides): Promise<string>;

  timedTask(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<TimeStructOutput>;

  callStatic: {
    cancelTask(taskId: BytesLike, overrides?: CallOverrides): Promise<void>;

    createTask(
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      feeToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    createTaskNoPrepayment(
      _execAddress: string,
      _execSelector: BytesLike,
      _resolverAddress: string,
      _resolverData: BytesLike,
      _feeToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    exec(
      taskCreator: string,
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      txFee: BigNumberish,
      feeToken: string,
      useTaskTreasuryFunds: boolean,
      revertOnFailure: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    gelato(overrides?: CallOverrides): Promise<string>;

    getFeeDetails(overrides?: CallOverrides): Promise<[BigNumber, string]>;

    getTaskIdsByUser(
      taskCreator: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    setModule(
      modules: BigNumberish[],
      moduleAddresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    taskTreasury(overrides?: CallOverrides): Promise<string>;

    timedTask(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<TimeStructOutput>;
  };

  filters: {};

  estimateGas: {
    cancelTask(
      taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createTask(
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      feeToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createTaskNoPrepayment(
      _execAddress: string,
      _execSelector: BytesLike,
      _resolverAddress: string,
      _resolverData: BytesLike,
      _feeToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exec(
      taskCreator: string,
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      txFee: BigNumberish,
      feeToken: string,
      useTaskTreasuryFunds: boolean,
      revertOnFailure: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    gelato(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeDetails(overrides?: CallOverrides): Promise<BigNumber>;

    getTaskIdsByUser(
      taskCreator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setModule(
      modules: BigNumberish[],
      moduleAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    taskTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    timedTask(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelTask(
      taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createTask(
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      feeToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createTaskNoPrepayment(
      _execAddress: string,
      _execSelector: BytesLike,
      _resolverAddress: string,
      _resolverData: BytesLike,
      _feeToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exec(
      taskCreator: string,
      execAddress: string,
      execData: BytesLike,
      moduleData: ModuleDataStruct,
      txFee: BigNumberish,
      feeToken: string,
      useTaskTreasuryFunds: boolean,
      revertOnFailure: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    gelato(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeeDetails(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTaskIdsByUser(
      taskCreator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setModule(
      modules: BigNumberish[],
      moduleAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    taskTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timedTask(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
